#!/usr/bin/env bash

set -eu -o pipefail

export TARGET="$WD/bin/main"

now () {
    date +%s.%N
}

build_all () {
    flags=(
        "-std=c99" \
        "-ferror-limit=1" \
        -O0 \
        -Werror \
        -Wall \
        -Wextra \
        -Wconversion \
        -Wsign-conversion \
        -Wunused \
        -Wunused-function \
        -Wunused-label \
        -Wunused-macros \
        -Wunused-parameter \
        -Wunused-value \
        -Wunused-variable \
        -Wcast-align \
        -Wcast-qual \
        -Wmissing-declarations \
        -Wredundant-decls \
        -Wmissing-prototypes \
        -Wnested-externs \
        -Wpointer-arith \
        -Wshadow \
        -Wstrict-prototypes \
        -Wwrite-strings \
        -Wswitch \
        -Wmissing-field-initializers \
        -pedantic-errors
    )
    srcs=(
        main
    )
    cp "$WD/src"/* "$WD/build"
    cd "$WD/build" || exit 1
    printf "Compiling %s\n" "${srcs[@]/%/.c}"
    clang "${flags[@]}" -lpthread "${srcs[@]/%/.c}" -o "$TARGET"
}

(
    start=$(now)
    clang-format -i -verbose "$WD/src"/* 2>&1 | sed 's/\/.*\///g'
    build_all
    end=$(now)
    python3 -c "print(\"Done! ({:.3f}s)\n\".format(${end} - ${start}))"
)

echo "$ $TARGET"
"$TARGET"
